"""initial schema

Revision ID: fdd94455f7d9
Revises: 
Create Date: 2026-04-23 14:08:00.832108
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'fdd94455f7d9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processes',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=False),
    sa.Column('surface', sa.String(length=32), nullable=False),
    sa.Column('phase', sa.String(length=32), nullable=False),
    sa.Column('chat_attached', sa.Boolean(), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('outputs', sa.JSON(), nullable=False),
    sa.Column('transition_types', sa.JSON(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('process_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_process_id'), 'chat_messages', ['process_id'], unique=False)
    op.create_table('dashboard_layouts',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('process_id', sa.String(length=64), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'process_id')
    )
    op.create_table('process_instances',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('process_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_state', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_instances_process_id'), 'process_instances', ['process_id'], unique=False)
    op.create_table('process_role_access',
    sa.Column('process_id', sa.String(length=64), nullable=False),
    sa.Column('role_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('process_id', 'role_id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('role_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('transitions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('process_instance_id', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('feeds_back', sa.Boolean(), nullable=False),
    sa.Column('retracted_by', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['process_instance_id'], ['process_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['retracted_by'], ['transitions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transitions_feeds_back'), 'transitions', ['feeds_back'], unique=False)
    op.create_index('ix_transitions_instance_ts', 'transitions', ['process_instance_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_transitions_process_instance_id'), 'transitions', ['process_instance_id'], unique=False)
    op.create_index(op.f('ix_transitions_retracted_by'), 'transitions', ['retracted_by'], unique=False)
    op.create_index(op.f('ix_transitions_timestamp'), 'transitions', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transitions_timestamp'), table_name='transitions')
    op.drop_index(op.f('ix_transitions_retracted_by'), table_name='transitions')
    op.drop_index(op.f('ix_transitions_process_instance_id'), table_name='transitions')
    op.drop_index('ix_transitions_instance_ts', table_name='transitions')
    op.drop_index(op.f('ix_transitions_feeds_back'), table_name='transitions')
    op.drop_table('transitions')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('process_role_access')
    op.drop_index(op.f('ix_process_instances_process_id'), table_name='process_instances')
    op.drop_table('process_instances')
    op.drop_table('dashboard_layouts')
    op.drop_index(op.f('ix_chat_messages_process_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('processes')
    # ### end Alembic commands ###
